# 개발 환경
FROM node:22-alpine3.18 as dev
RUN apk --update add postgresql-client

WORKDIR /usr/src/app

COPY package*.json ./

# 개발 환경에서 필요한 모든 패키지 설치
RUN npm install
RUN npm install glob rimraf cross-env

COPY . .

RUN npm run build

# 프로덕션 환경
FROM node:fermium-alpine as prod
RUN apk --update add postgresql-client

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

# 프로덕션 환경에서 필요한 패키지 설치
RUN npm install --production
RUN npm install --production cross-env

COPY . .

COPY --from=dev /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
