global:
  scrape_interval: 15s # 모든 타겟을 기본적으로 15초마다 스크랩

scrape_configs:
  - job_name: 'prometheus' # 작업 이름
    static_configs:
      - targets: ['localhost:9090'] # Prometheus 서버 자체의 메트릭을 수집

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Node Exporter 타겟 설정

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # cAdvisor 타겟 설정

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113'] # Nginx Exporter 타겟 설정

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216'] # MongoDB Exporter 타겟 설정

  - job_name: 'blackbox-exporter'
    metrics_path: /probe # 메트릭 경로
    params:
      module: [http_2xx] # Blackbox Exporter에서 사용할 모듈 설정
    static_configs:
      - targets: ['http://localhost:8080'] # HTTP 모니터링 타겟 (예: localhost의 8080 포트)
    relabel_configs:
      - source_labels: [__address__] # 원본 주소 라벨
        target_label: __param_target # 타겟 라벨 설정
      - source_labels: [__param_target] # 원본 타겟 라벨
        target_label: instance # 인스턴스 라벨 설정
      - target_label: __address__ # 주소 라벨
        replacement: blackbox-exporter:9115 # Blackbox Exporter 주소 설정

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14268'] # Jaeger 타겟 설정

  - job_name: 'wilsoto-nestjs-prometheus'
    static_configs:
      - targets: ['nestjs-prometheus:3001'] # NestJS Prometheus 타겟 설정
