global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_load:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter_load:9100']

  - job_name: 'nestjs'
    static_configs:
      - targets: ['nestjs_app_load:3000']
