version: '3.8'

services:
  redis1:
    hostname: redis1
    container_name: redis1
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6300:6379 # 컨테이너 내부에서는 여전히 6379 포트를 사용합니다.
      - 16300:16300

  redis2:
    hostname: redis2
    container_name: redis2
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6301:6379
      - 16301:16301

  redis3:
    hostname: redis3
    container_name: redis3
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6302:6379
      - 16302:16302

  redis4:
    hostname: redis4
    container_name: redis4
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6400:6379
      - 16400:16400

  redis5:
    hostname: redis5
    container_name: redis5
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6401:6379
      - 16401:16401

  redis6:
    hostname: redis6
    container_name: redis6
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6402:6379
      - 16402:16402
