version: '3.8'

services:
  redis-master1:
    container_name: redis-master1
    image: redis
    restart: always
    command: redis-server /etc/redis-master1.conf
    volumes:
      - ./master/redis-master1.conf:/etc/redis-master1.conf
    ports:
      - 7000:7000
      - 17000:17000
    networks:
      - redis-cluster-net

  redis-master2:
    container_name: redis-master2
    image: redis
    restart: always
    command: redis-server /etc/redis-master2.conf
    volumes:
      - ./master/redis-master2.conf:/etc/redis-master2.conf
    ports:
      - 7001:7001
      - 17001:17001
    networks:
      - redis-cluster-net

  redis-master3:
    container_name: redis-master3
    image: redis
    restart: always
    command: redis-server /etc/redis-master3.conf
    volumes:
      - ./master/redis-master3.conf:/etc/redis-master3.conf
    ports:
      - 7002:7002
      - 17002:17002
    networks:
      - redis-cluster-net

  redis-slave1:
    container_name: redis-slave1
    image: redis:latest
    restart: always
    volumes:
      - ./slave/redis-slave1.conf:/etc/redis-slave1.conf
    command: redis-server /etc/redis-slave1.conf
    ports:
      - 7100:7100
      - 17100:17100
    networks:
      - redis-cluster-net

  redis-slave2:
    container_name: redis-slave2
    image: redis:latest
    restart: always
    volumes:
      - ./slave/redis-slave2.conf:/etc/redis-slave2.conf
    command: redis-server /etc/redis-slave2.conf
    ports:
      - 7101:7101
      - 17101:17101
    networks:
      - redis-cluster-net

  redis-slave3:
    container_name: redis-slave3
    image: redis:latest
    restart: always
    volumes:
      - ./slave/redis-slave3.conf:/etc/redis-slave3.conf
    command: redis-server /etc/redis-slave3.conf
    ports:
      - 7102:7102
      - 17102:17102
    networks:
      - redis-cluster-net

  redis_cluster_entry:
    image: redis:latest
    container_name: redis_cluster_entry
    command: >
      sh -c "
      sleep 10;
      redis-cli --cluster create
      redis-master1:7000
      redis-master2:7001
      redis-master3:7002
      redis-slave1:7100
      redis-slave2:7101
      redis-slave3:7102
      --cluster-replicas 1
      --cluster-yes"
    depends_on:
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge
