version: '3.8'

services:
  controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    volumes:
      - ~/ngrinder-controller:/opt/ngrinder-controller
    ports:
      - "81:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    environment:
      - TZ=Asia/Seoul

  agent1:
    image: ngrinder/agent
    container_name: ngrinder-agent1
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent2:
    image: ngrinder/agent
    container_name: ngrinder-agent2
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent3:
    image: ngrinder/agent
    container_name: ngrinder-agent3
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent4:
    image: ngrinder/agent
    container_name: ngrinder-agent4
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent5:
    image: ngrinder/agent
    container_name: ngrinder-agent5
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent6:
    image: ngrinder/agent
    container_name: ngrinder-agent6
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent7:
    image: ngrinder/agent
    container_name: ngrinder-agent7
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent8:
    image: ngrinder/agent
    container_name: ngrinder-agent8
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent9:
    image: ngrinder/agent
    container_name: ngrinder-agent9
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller

  agent10:
    image: ngrinder/agent
    container_name: ngrinder-agent10
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    links:
      - controller
