version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariauser
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    # volumes:
    #   - mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '5051:8080'
    depends_on:
      - mariadb
      - postgres
# volumes:
#   mariadb_data:
#   postgres_data:
